config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get :new_session, to: "welcome#new"
  post :sign_in, to: "welcome#sign_in"
  resources :books, only: [ :index, :create, :update, :new ] do
    member do
      post :claim
      post :unclaim
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  before_update :sanitize_user_name

  def is_claimed?
    user_name.present?
  end

  def is_claimed_by?(name)
    name == user_name
  end

  private

  def sanitize_user_name
    self.user_name = ActionController::Base.helpers.sanitize(user_name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  http_basic_authenticate_with name: "paul", password: "secret", only: [ :create, :new ]
  before_action :set_user
  before_action :check_authentication, only: [ :claim, :unclaim ]
  before_action :set_book!, only: [ :claim, :unclaim ]
  after_action only: :claim do
    Turbo::StreamsChannel.broadcast_replace_later_to("books",
      target: "claim_#{helpers.dom_id(@book)}",
      partial: "books/just_claimed",
      locals: { book: @book }
    )
  end
  after_action only: :unclaim do
    Turbo::StreamsChannel.broadcast_replace_later_to("books",
      target: "just_claimed_#{helpers.dom_id(@book)}",
      partial: "books/claim",
      locals: { book: @book }
    )
  end

  class AuthenticationError < StandardError
  end

  class AuthorizationError < StandardError
  end

  def index
    redirect_to new_session_path and return unless @is_authenticated

    @books = Book.all
  end

  def create
    params[:message].split("\n").each do |line|
      title, author = line.split(",")
      Book.create(title: title, author: author)
    end
  end

  def claim
    raise StandardError if @book.is_claimed?

    @book.update!(user_name: @user_name)
    render partial: "form", locals: { book: @book, can_unclaim: @book.is_claimed_by?(@user_name) }
  rescue
    render partial: "error", locals: { book: @book }
  end

  def unclaim
    raise AuthorizationError unless @book.is_claimed_by?(@user_name)

    @book.update!(user_name: nil)
    render partial: "form", locals: { book: @book, can_unclaim: @book.is_claimed_by?(@user_name) }
  end

  def new
  end

  private

  def set_book!
    @book = Book.find_by!(id: params[:id])
  end

  def set_user
    @user_name = cookies[:user_name]
    @is_authenticated = @user_name.present?
  end

  def check_authentication
    raise AuthenticationError unless @user_name.present?
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def new
  end

  def sign_in
    # TODO: remove numbers etc
    cookies[:user_name] = params[:user_name]
    redirect_to books_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_claim.html.haml
= link_to "Claim book", claim_book_path(book.id), data: { turbo_method: "post" }, id: "claim_#{dom_id(book)}"

app/views/books/_error.html.haml
%turbo-frame{id: dom_id(book)}
  %p
    This book as already been claimed

app/views/books/_form.html.haml
%turbo-frame{id: dom_id(book)}
  - if book.is_claimed?
    - if can_unclaim
      = link_to "Annuler", unclaim_book_path(book.id), data: { turbo_method: "post" }, class: 'btn btn-outline btn-neutral w-24'
    - else
      = button_tag "Réservé", type: 'button', disabled: true, class: 'btn w-24'

  - else
    -# = link_to "Réserver", claim_book_path(book.id), data: { turbo_method: "post" }, id: "claim_#{dom_id(book)}"
    = button_to "Réserver", claim_book_path(book.id), method: :post, class: 'btn btn-accent w-24'

app/views/books/_just_claimed.html.haml
%div{id: "just_claimed_#{dom_id(book)}"}
  This book just got claimed!

app/views/books/index.html.haml
= turbo_stream_from "books"

%h1 Réservez-moi !

.flex.flex-col.gap-2
  - @books.each do |book|
    .flex.flex-row.justify-between.gap-4
      %div.leading-tight
        %span.font-semibold<
          = book.title
          %span.font-normal ,
        %span
          = book.author
      %div
        = render partial: "form", locals: { book: book, can_unclaim: book.is_claimed_by?(@user_name) }

app/views/books/new.html.haml
%h1 Books#new
%p Find me in app/views/books/new.html.erb

= form_with url: books_path, method: :post do |form|
  = form.text_area :message, size: "70x5"
  = form.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Books Giveaway"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "yes", :name => "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    -# = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"

  %body.h-screen
    .relative.h-full
      .absolute.inset-0.bg-white.opacity-90
      %main.container.py-4.md:py-8.prose.z-20.relative
        = yield

app/views/welcome/index.html.haml
%h1 Salut !

%details
  %summary.cursor-pointer.outline-none.select-none J'ai pas mal de bouquins chez moi.
  = image_tag "books.jpg", style: "max-width: 100%"

%p Je vais m'en séparer !

%p Si tu les veux, fais-toi plaisir.

.flex.justify-center
  = link_to "Réserver un livre", books_path, class: 'btn btn-lg no-underline'

app/views/welcome/new.html.haml
%h2 Qui es-tu ?

= form_with url: sign_in_path, local: true, method: :post, class: 'flex flex-col sm:flex-row justify-between gap-4' do |form|
  = form.text_field :user_name, autocomplete: 'off', required: true, pattern: ".*[a-zA-Z].*", autofocus: true, class: 'input input-bordered w-full'
  = form.submit "Enregistrer", class: :btn